---
- name: Configure Windows network before/after migration
  hosts: win-mig
  ignore_errors: true
  gather_facts: yes
  collections: 
    - ansible.windows
  vars:
    win_user: "Administrator"
    win_pass: "Vodafone@12345"
    new_gateway: "10.85.50.17,10.85.50.29"
    interface_name: "Ethernet" 
    proxy_url: "http://10.38.107.203:3120"

  tasks:
    - name: Set WinRM connection
      ansible.builtin.set_fact:
        ansible_user: "{{ win_user }}"
        ansible_password: "{{ win_pass }}"
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_port: 5985



    - name: Configure persistent system-wide proxy
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings
        name: ProxyServer
        data: "{{ proxy_url }}"
        type: string

    - name: Enable proxy
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings
        name: ProxyEnable
        data: 1
        type: dword
    - name: Set WinHTTP proxy
      ansible.windows.win_shell: |
        netsh winhttp set proxy "{{ proxy_url }}"
 
    - name: Refresh settings
      ansible.windows.win_shell: |
        RUNDLL32.EXE USER32.DLL,UpdatePerUserSystemParameters
