---
- name: Set up passwordless SSH authentication on Ubuntu hosts
  hosts: remote
  become: false
  vars:
    ssh_key_path: "~/.ssh/id_rsa.pub"   # Path to the public key on the Ansible control node

  tasks:

    - name: Ensure SSH key exists
      ansible.builtin.stat:
        path: /root/.ssh/id_rsa
      register: ssh_key

    - name: Generate SSH key if not present
      ansible.builtin.command: ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N ""
      when: not ssh_key.stat.exists


    - name: Read public key content
      delegate_to: localhost
      slurp:
        src: "{{ ssh_key_path }}"
      register: public_key

    - name: Add public key to authorized_keys on remote hosts
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ public_key.content | b64decode }}"
        state: present

    - name: Verify passwordless SSH works
      command: whoami
      register: ssh_test

    - name: Display result
      debug:
        msg: "Passwordless SSH setup for {{ inventory_hostname }}: {{ ssh_test.stdout }}"
