---
- name: Deploy DNS servers
  hosts: keepha
  become: yes
  roles:
    - dns-role

#- name: Deploy HAProxy
#  hosts: dns_servers
#  become: yes
#  roles:
#    - haproxy
 
#- name: Configure NTP on all nodes
#  hosts: all
#  become: yes
#  roles:
#    - ntp
