---
- name: Install HashiCorp Vault, Terraform, and Packer on AlmaLinux 9
  hosts: vault
  become: true
  vars:
    hashicorp_repo_url: "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"

  tasks:
    - name: 🧾 Ensure system is AlmaLinux 9
      ansible.builtin.assert:
        that:
          - ansible_facts['os_family'] == "RedHat"
          - ansible_facts['distribution_major_version'] == "9"
        fail_msg: "❌ This playbook is only supported on AlmaLinux 9 or RHEL 9"
        success_msg: "✅ AlmaLinux 9 detected"

    - name: 📦 Install required dependencies
      ansible.builtin.package:
        name:
          - yum-utils
          - dnf-plugins-core
          - curl
        state: present

    - name: 🗂️ Add HashiCorp repository
      ansible.builtin.get_url:
        url: "{{ hashicorp_repo_url }}"
        dest: /etc/yum.repos.d/hashicorp.repo
        mode: '0644'

    - name: 🔁 Clean DNF cache
      ansible.builtin.command: dnf clean all
      args:
        warn: false

    - name: 📥 Install Vault, Terraform, and Packer
      ansible.builtin.package:
        name:
          - vault
          - terraform
          - packer
        state: present
      register: install_result

    - name: 🧩 Display installation summary
      ansible.builtin.debug:
        msg:
          - "✅ HashiCorp tools installed successfully"
          - "Installed packages: {{ install_result.results | map(attribute='name') | list }}"

    - name: 🔍 Verify Vault installation
      ansible.builtin.command: vault --version
      register: vault_ver
      changed_when: false
      ignore_errors: true

    - name: 🔍 Verify Terraform installation
      ansible.builtin.command: terraform version
      register: terraform_ver
      changed_when: false
      ignore_errors: true

    - name: 🔍 Verify Packer installation
      ansible.builtin.command: packer version
      register: packer_ver
      changed_when: false
      ignore_errors: true

    - name: 📊 Show versions summary
      ansible.builtin.debug:
        msg:
          - "Vault Version: {{ vault_ver.stdout | default('Not Installed') }}"
          - "Terraform Version: {{ terraform_ver.stdout | default('Not Installed') }}"
          - "Packer Version: {{ packer_ver.stdout | default('Not Installed') }}"

