---
- name: Configure passwordless SSH and sudo for Ansible user
  hosts: all
  become: true
  vars:
    ansible_user: root                # Initial SSH user (with password access)
    target_user: root                 # User for Ansible automation
    #    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"  # Use your local key
    # if using RSA key instead:
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:

    - name: Ensure target user exists
      ansible.builtin.user:
        name: "{{ target_user }}"
        comment: "Ansible Managed User"
        shell: /bin/bash
        create_home: yes
        groups: wheel
        append: yes

    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ target_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Add controller’s public key for passwordless SSH
      ansible.builtin.copy:
        content: "{{ ssh_pub_key }}"
        dest: "/home/{{ target_user }}/.ssh/authorized_keys"
        mode: '0600'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Allow passwordless sudo for the target user
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ target_user }}"
        content: "{{ target_user }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'

    - name: Verify sudo access
      ansible.builtin.command: whoami
      become_user: "{{ target_user }}"
      register: whoami_output

    - name: Show verification result
      ansible.builtin.debug:
        msg: "User '{{ target_user }}' can sudo as '{{ whoami_output.stdout }}'"

