---
- name: Install Keepalived
  ansible.builtin.yum:
    name: keepalived
    state: present

- name: Configure Keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'

- name: Enable and restart Keepalived
  ansible.builtin.systemd:
    name: keepalived
    enabled: yes
    state: restarted

