---
- name: Install HashiCorp Vault, Terraform, and Packer on RHEL / AlmaLinux / Rocky 9
  hosts: vault
  vars:
    hashicorp_repo_url: "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"

  tasks:
    - name: 📦 Install required dependencies
      ansible.builtin.dnf:
        name:
          - yum-utils
          - dnf-plugins-core
          - curl
        state: present

    - name: 🗂️ Add HashiCorp repository
      ansible.builtin.get_url:
        url: "{{ hashicorp_repo_url }}"
        dest: /etc/yum.repos.d/hashicorp.repo
        mode: '0644'


    - name: 📥 Install Vault, Terraform, and Packer
      ansible.builtin.dnf:
        name:
          - vault
          - terraform
          - packer
        state: present
      register: install_result

    - name: 🧩 Display installation summary
      ansible.builtin.debug:
        msg:
          - "✅ HashiCorp tools installed successfully"
          - "Installed packages: vault, terraform, packer"

    - name: 🔍 Verify Vault installation
      ansible.builtin.command: vault --version
      register: vault_ver
      changed_when: false
      ignore_errors: true

    - name: 🔍 Verify Terraform installation
      ansible.builtin.command: terraform version
      register: terraform_ver
      changed_when: false
      ignore_errors: true

    - name: 🔍 Verify Packer installation
      ansible.builtin.command: packer version
      register: packer_ver
      changed_when: false
      ignore_errors: true

    - name: 📊 Show versions summary
      ansible.builtin.debug:
        msg:
          - "Vault Version: {{ vault_ver.stdout | default('Not Installed') }}"
          - "Terraform Version: {{ terraform_ver.stdout | default('Not Installed') }}"
          - "Packer Version: {{ packer_ver.stdout | default('Not Installed') }}"
